const state={screen:'home',users:[],videos:[],currentUser:{id:'local-user',username:'owen',displayName:'Owen',bio:'Building Owen.',followers:0,following:0,likes:0},following:new Set(),likes:new Set(),comments:{}};
const app=document.getElementById('app');
function render(){app.innerHTML=`<div class="app"><section id="home" class="screen active"><div class="feed" id="feed"></div></section><section id="search" class="screen"><div class="page"><div class="title">Search</div><input id="q" class="input" placeholder="Search people or hashtags..."><div id="results"></div></div></section><section id="create" class="screen"><div class="page"><div class="title">Create</div><div class="card"><input id="videoFile" class="input" type="file" accept="video/*"><input id="caption" class="input" placeholder="Write a caption..."><input id="tags" class="input" placeholder="#hashtags"><button id="post" class="btn">Add video</button><p id="status"></p></div></div></section><section id="inbox" class="screen"><div class="page"><div class="title">Inbox</div><div id="notifications" class="card">No notifications yet.</div></div></section><section id="profile" class="screen"><div class="profileTop" id="myProfile"></div><div class="page"><h3>Your videos</h3><div id="myGrid" class="grid"></div></div></section><section id="person" class="screen"><div class="profileTop" id="personProfile"></div><div class="page"><button id="back" class="btn">← Back</button><h3>Videos</h3><div id="personGrid" class="grid"></div></div></section><nav class="nav"><button data-s="home">🏠<b>Home</b></button><button data-s="search">🔎<b>Search</b></button><button data-s="create">＋<b>Create</b></button><button data-s="inbox">♡<b>Inbox</b></button><button data-s="profile">●<b>Profile</b></button></nav></div>`;bind();renderFeed();renderProfile();show('home')}
function bind(){document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>show(b.dataset.s));document.getElementById('q').oninput=e=>search(e.target.value);document.getElementById('post').onclick=postVideo;document.getElementById('back').onclick=()=>show('search')}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.s===id));state.screen=id}
function renderFeed(){const f=document.getElementById('feed');if(!state.videos.length){f.innerHTML='<div class="empty">No videos yet.<br><br>Go to <b>Create</b> and add your first video.</div>';return}f.innerHTML=state.videos.map(v=>`<article class="video"><video src="${v.url}" playsinline loop muted preload="metadata"></video><div class="overlay"><b>@${esc(v.username)}</b><div>${esc(v.caption)}</div><small>${esc(v.tags)}</small></div><div class="actions"><button class="action" data-like="${v.id}">♡</button><span class="count">${v.likes}</span><button class="action" data-comment="${v.id}">💬</button><span class="count">${(state.comments[v.id]||[]).length}</span></div></article>`).join('');f.querySelectorAll('video').forEach(v=>v.onclick=()=>{v.muted=!v.muted;if(v.paused)v.play();});f.querySelectorAll('[data-like]').forEach(b=>b.onclick=()=>like(b.dataset.like));f.querySelectorAll('[data-comment]').forEach(b=>b.onclick=()=>comment(b.dataset.comment));const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.play().catch(()=>{});else e.target.pause()}),{threshold:.7});f.querySelectorAll('video').forEach(v=>obs.observe(v))}
function search(q){const r=document.getElementById('results');q=q.trim().toLowerCase();if(!q){r.innerHTML='<div class="card">Search uses the users stored in Owen. New accounts will appear here when the account system is connected.</div>';return}const users=state.users.filter(u=>u.username.includes(q)||u.displayName.toLowerCase().includes(q));r.innerHTML=users.length?users.map(u=>`<div class="card user" data-user="${u.id}"><div class="avatar">${esc(u.displayName[0]||'U')}</div><div><b>@${esc(u.username)}</b><div style="color:#aaa">${esc(u.displayName)}</div></div></div>`).join(''):'<div class="card">No user found.</div>';r.querySelectorAll('[data-user]').forEach(x=>x.onclick=()=>openUser(x.dataset.user))}
function openUser(id){const u=state.users.find(x=>x.id===id);if(!u)return;document.getElementById('personProfile').innerHTML=`<div class="user"><div class="avatar">${esc(u.displayName[0]||'U')}</div><div><h2>@${esc(u.username)}</h2><div>${esc(u.bio)}</div></div></div><div class="stats"><div><b>${u.followers}</b><span>followers</span></div><div><b>${u.following}</b><span>following</span></div><div><b>${u.likes}</b><span>likes</span></div></div><button id="follow" class="btn">${state.following.has(id)?'Following':'Follow'}</button>`;document.getElementById('follow').onclick=()=>toggleFollow(id);document.getElementById('personGrid').innerHTML=state.videos.filter(v=>v.userId===id).map(v=>'<div class="tile">▶</div>').join('')||'<div class="empty">No videos yet.</div>';show('person')}
function toggleFollow(id){if(state.following.has(id))state.following.delete(id);else state.following.add(id);openUser(id)}
function like(id){if(state.likes.has(id))return;state.likes.add(id);const v=state.videos.find(x=>x.id===id);if(v){v.likes++;state.currentUser.likes++;save();renderFeed()}}
function comment(id){const c=prompt('Comment');if(!c)return;(state.comments[id]??=[]).push({id:crypto.randomUUID(),userId:state.currentUser.id,text:c,time:Date.now()});save();renderFeed()}
function postVideo(){const file=document.getElementById('videoFile').files[0];if(!file){document.getElementById('status').textContent='Choose a video first.';return}const v={id:crypto.randomUUID(),userId:state.currentUser.id,username:state.currentUser.username,caption:document.getElementById('caption').value||'',tags:document.getElementById('tags').value||'',likes:0,url:URL.createObjectURL(file)};state.videos.unshift(v);document.getElementById('status').textContent='Video added locally. It has 0 likes until someone actually likes it.';renderFeed();show('home');save()}
function renderProfile(){const u=state.currentUser;document.getElementById('myProfile').innerHTML=`<div class="user"><div class="avatar">${esc(u.displayName[0])}</div><div><h2>@${esc(u.username)}</h2><div>${esc(u.bio)}</div></div></div><div class="stats"><div><b>${u.followers}</b><span>followers</span></div><div><b>${u.following}</b><span>following</span></div><div><b>${u.likes}</b><span>likes</span></div></div>`;document.getElementById('myGrid').innerHTML=state.videos.filter(v=>v.userId===u.id).map(v=>'<div class="tile">▶</div>').join('')||'<div class="empty">No videos yet.</div>'}
function save(){localStorage.setItem('owenLite',JSON.stringify({videos:state.videos.map(v=>({...v,url:null})),currentUser:state.currentUser,following:[...state.following],likes:[...state.likes],comments:state.comments}))}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
render();
